### ISSUE TITLE
Lacks ocamlbuild

### ISSUE THREAD

**Issue by whitequark** [OCamlPro/ocpwin-distrib#3]
ocamlbuild is a component of the compiler and is used in the vast majority of libraries I use. Why is it not included in the package?

**Comment by gasche** [comment]
For the report, I would be happy to help upstream changes to make OCamlbuild work better on Windows (we've already made a few of them), even though I don't know much about Windows environments myself. What is needed is someone willing to invest a bit of work in testing and changing what needs to be changed (not that much, and code from [Oasis](https://github.com/ocaml/oasis/blob/master/src/oasis/OASISFileUtil.ml) could be reused).
